### ISSUE TITLE
Also upload `.dsc` files

### ISSUE THREAD

**Issue by m-roberts** [lpenz/ghaction-packagecloud#1]
`.dsc` files are also useful in PackageCloud. It would be great if there was a way to easily include this as well.

**Comment by m-roberts** [comment]
```
You can't push multiple packages of different types at the same time.
For example, use *.deb to push all your debs at once.
```

This needs to be done in a separate action:
```
      - uses: docker://lpenz/ghaction-packagecloud:v0.3
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: docker://lpenz/ghaction-packagecloud:v0.3
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}
          files: ./artifacts/file.dsc
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
```
