### ISSUE TITLE
Add pattern matching support for `files` input

### ISSUE THREAD

**Issue by m-roberts** [lpenz/ghaction-packagecloud#3]
```
      - uses: docker://lpenz/ghaction-packagecloud:v0.3
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}/${{ env.OS }}/${{ env.DISTRO }}
          files: ./artifacts/*.dsc
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
```
This does not work as `./artifacts/*.dsc` is evaluated literally. This requires an additional previous step to determine the actual path.

For similar context, other actions support this:
```
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.CURRENT_VERSION }}"
          name: "v${{ env.CURRENT_VERSION }}"
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
