### ISSUE TITLE
Error: deb packages require an operating system and version to be selected.

### ISSUE THREAD

**Issue by tidusjar** [lpenz/ghaction-packagecloud#5]
I'm gettting the following error:

```
/usr/local/bundle/gems/json_pure-1.8.1/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/usr/local/bundle/gems/package_cloud-0.3.08/lib/package_cloud/validator.rb:61:in `get_valid': undefined method `chomp' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/package_cloud-0.3.08/lib/package_cloud/validator.rb:46:in `select_from'
	from /usr/local/bundle/gems/package_cloud-0.3.08/lib/package_cloud/validator.rb:78:in `select_dist'
	from /usr/local/bundle/gems/package_cloud-0.3.08/lib/package_cloud/validator.rb:33:in `distribution_id'
	from /usr/local/bundle/gems/package_cloud-0.3.08/lib/package_cloud/cli/entry.rb:158:in `block in push'
	from /usr/local/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
	from /usr/local/bundle/gems/package_cloud-0.3.08/lib/package_cloud/cli/entry.rb:109:in `push'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/package_cloud-0.3.08/bin/package_cloud:4:in `<top (required)>'
	from /usr/local/bundle/bin/package_cloud:23:in `load'
	from /usr/local/bundle/bin/package_cloud:23:in `<main>'
Using https://packagecloud.io with token:******c54f
deb packages require an operating system and version to be selected.

If you don't see your OS or version here, send us an email at support@packagecloud.io:

	0. Ubuntu
	1. Debian
	2. LinuxMint
	3. Raspbian
	4. elementary OS

 0-4: 
```

when using this config:

```
      - name: Package Cloud Deploy
        uses: docker://lpenz/ghaction-packagecloud:v0.2
        with:
          repository: ombi-app/Ombi
          directory: ./repo/public
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
```

You can see this here: https://github.com/Ombi-app/Ombi.Apt/runs/3858349194?check_suite_focus=true
